from apps.dashboards.services.comparison import _build_assistant_comparison_table
from apps.dashboards.services.comparison import _build_assistant_detail_comparison
from apps.dashboards.services.comparison import _build_churn_reason_comparison_table
from apps.dashboards.services.comparison import _build_comparison_block
from apps.dashboards.services.comparison import _build_inconsistency_comparison_section
from apps.dashboards.services.comparison import _build_retention_action_comparison_table
from apps.dashboards.services.comparison import _build_service_type_comparison_table
from apps.dashboards.services.comparison import _compute_delta
from apps.dashboards.services.comparison import _resolve_previous_period
from apps.dashboards.services.insights import generate_insights  # noqa: F401
from apps.dashboards.services.payload import _build_table_states
from apps.dashboards.services.payload import _build_ui_state
from apps.dashboards.services.payload import _take_top
from apps.dashboards.services.payload import build_assistant_detail
from apps.dashboards.services.payload import build_dashboard_payload
from apps.dashboards.services.payload import build_frontend_payload
from apps.dashboards.services.tables import _apply_status_badges
from apps.dashboards.services.tables import _iter_periods
from apps.dashboards.services.tables import _normalize_period
from apps.dashboards.services.tables import _pct
from apps.dashboards.services.tables import _round2
from apps.dashboards.services.tables import _totals_with_non_retained
from apps.dashboards.services.tables import build_assistant_ranking_table
from apps.dashboards.services.tables import build_churn_reason_table
from apps.dashboards.services.tables import build_daily_rates_summary
from apps.dashboards.services.tables import build_daily_rates_table
from apps.dashboards.services.tables import build_inconsistency_section
from apps.dashboards.services.tables import build_monthly_rates_summary
from apps.dashboards.services.tables import build_monthly_rates_table
from apps.dashboards.services.tables import build_retention_action_table
from apps.dashboards.services.tables import build_service_type_table
from apps.dashboards.services.tables import build_temporal_table
from apps.dashboards.services.tables import build_tipification_tables
from apps.dashboards.services.tables import calculate_general_kpis
from apps.dashboards.services.tables import get_status_class