# Generated by Django 6.0.3 on 2026-04-02 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importbatch',
            options={'ordering': ['-imported_at']},
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='imported_rows',
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='uploaded_filename',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='error_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='failed_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='flagged_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_schema_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_type',
            field=models.CharField(choices=[('manual_excel', 'Manual Excel'), ('csv', 'CSV'), ('api', 'API')], default='manual_excel', max_length=30),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='stored_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='success_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ImportRowRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField()),
                ('raw_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='imports_app.importbatch')),
            ],
            options={
                'ordering': ['batch_id', 'source_row_number'],
            },
        ),
    ]
