# Generated by Django 6.0.3 on 2026-04-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_app', '0002_alter_importbatch_options_and_more'),
        ('inbound', '0002_agent_churnreason_outcomefinal_retentionaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrowraw',
            name='processed_interaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_row', to='inbound.interaction'),
        ),
        migrations.AddConstraint(
            model_name='importrowraw',
            constraint=models.UniqueConstraint(fields=('batch', 'source_row_number'), name='unique_raw_row_per_batch'),
        ),
    ]
