# Generated by Django 6.0.3 on 2026-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_app', '0003_importrowraw_processed_interaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrowraw',
            name='raw_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
