# Generated by Django 6.0.3 on 2026-04-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_app', '0004_alter_importrowraw_raw_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='duplicate_in_file_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='duplicate_previous_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='duplicate_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrowraw',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importrowraw',
            name='processing_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('duplicate_in_file', 'Duplicate In File'), ('duplicate_previous', 'Duplicate Previous'), ('failed_validation', 'Failed Validation')], default='imported', max_length=30),
        ),
    ]
