# Generated by Django 6.0.3 on 2026-04-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_app', '0005_importbatch_duplicate_in_file_rows_and_more'),
        ('inbound', '0007_outboundinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrowraw',
            name='processed_outbound_interaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_row', to='inbound.outboundinteraction'),
        ),
    ]
