from django.urls import path

from apps.dashboards.views import (
    agent_dashboard,
    assistant_detail,
    assistants_csv,
    assistants,
    churn_reasons,
    daily_rates_csv,
    daily_rates,
    insights,
    inconsistencies_csv,
    inconsistencies,
    monthly_rates_csv,
    monthly_rates,
    overview,
    previous_day,
    previous_day_export,
    retention_actions,
    services_csv,
    services,
    team_dashboard,
    typing_analysis,
    typing_analysis_excel,
)

app_name = 'dashboards'

urlpatterns = [
    path('', overview, name='index'),
    path('overview/', overview, name='overview'),
    path('churn-reasons/', churn_reasons, name='churn_reasons'),
    path('retention-actions/', retention_actions, name='retention_actions'),
    path('services/', services, name='services'),
    path('services/export.csv', services_csv, name='services_csv'),
    path('assistants/', assistants, name='assistants'),
    path('assistants/export.csv', assistants_csv, name='assistants_csv'),
    path('assistants/<int:assistant_id>/', assistant_detail, name='assistant_detail'),
    path('inconsistencies/', inconsistencies, name='inconsistencies'),
    path('inconsistencies/export.csv', inconsistencies_csv, name='inconsistencies_csv'),
    path('insights/', insights, name='insights'),
    path('monthly-rates/', monthly_rates, name='monthly_rates'),
    path('monthly-rates/export.csv', monthly_rates_csv, name='monthly_rates_csv'),
    path('daily-rates/', daily_rates, name='daily_rates'),
    path('daily-rates/export.csv', daily_rates_csv, name='daily_rates_csv'),
    path('previous-day/', previous_day, name='previous_day'),
    path('previous-day/export.xlsx', previous_day_export, name='previous_day_export'),
    path('teams/', team_dashboard, name='team_dashboard'),
    path('agents/', agent_dashboard, name='agent_dashboard'),
    path('typing-analysis/', typing_analysis, name='typing_analysis'),
    path('typing-analysis/export.xlsx', typing_analysis_excel, name='typing_analysis_excel'),
]
