# Generated by Django 6.0.3 on 2026-04-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_call_id', models.CharField(blank=True, max_length=100)),
                ('team_name', models.CharField(max_length=120)),
                ('agent_name', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('ret_resolution', models.CharField(db_index=True, max_length=120)),
                ('resolution', models.CharField(db_index=True, max_length=120)),
                ('third_category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('service_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('call_drop', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('source_file_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='imports_app.importbatch')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
