# Generated by Django 6.0.3 on 2026-04-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_app', '0002_alter_importbatch_options_and_more'),
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['team__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChurnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('category_group', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('is_call_drop_outcome', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='RetentionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('is_pending', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='batch',
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=20)),
                ('call_id_external', models.CharField(blank=True, max_length=100)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('occurred_on', models.DateField(db_index=True)),
                ('is_call_drop', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='inbound.agent')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='imports_app.importbatch')),
                ('churn_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='inbound.churnreason')),
                ('final_outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='inbound.outcomefinal')),
                ('retention_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='inbound.retentionaction')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='inbound.servicetype')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='inbound.team')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='inbound.team'),
        ),
    ]
