# Generated by Django 6.0.3 on 2026-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_agent_churnreason_outcomefinal_retentionaction_and_more'),
        ('quality', '0002_dataqualityflag_delete_tipificationinconsistency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallRecord',
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['direction', 'occurred_on'], name='inbound_int_directi_d3f9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['team', 'occurred_on'], name='inbound_int_team_id_940cae_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['agent', 'occurred_on'], name='inbound_int_agent_i_c87a75_idx'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='interaction_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='unique_agent_name_per_team'),
        ),
    ]
