# Generated by Django 6.0.3 on 2026-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0005_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='interaction',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='subcategory',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
