# Generated by Django 6.0.3 on 2026-04-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports_app', '0005_importbatch_duplicate_in_file_rows_and_more'),
        ('inbound', '0006_interaction_typing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id_external', models.CharField(blank=True, max_length=100)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('occurred_on', models.DateField(db_index=True)),
                ('is_call_drop', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=200)),
                ('observations', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_interactions', to='inbound.agent')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_interactions', to='imports_app.importbatch')),
                ('churn_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_interactions', to='inbound.churnreason')),
                ('final_outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_interactions', to='inbound.outcomefinal')),
                ('retention_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_interactions', to='inbound.retentionaction')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_interactions', to='inbound.servicetype')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_interactions', to='inbound.team')),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['occurred_on'], name='inbound_out_occurre_4cc5cd_idx'), models.Index(fields=['category'], name='inbound_out_categor_b24161_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='outbound_interaction_end_after_start')],
            },
        ),
    ]
