# Generated by Django 6.0.3 on 2026-04-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipificationInconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipification_inconsistency', to='inbound.callrecord')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
