# Generated by Django 6.0.3 on 2026-04-02 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_agent_churnreason_outcomefinal_retentionaction_and_more'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('tipification_inconsistency', 'Tipification Inconsistency'), ('duration_invalid', 'Duration Invalid'), ('missing_required', 'Missing Required')], max_length=50)),
                ('rule_code', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_flags', to='inbound.interaction')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_quality_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.DeleteModel(
            name='TipificationInconsistency',
        ),
        migrations.AddIndex(
            model_name='dataqualityflag',
            index=models.Index(fields=['flag_type', 'severity'], name='quality_dat_flag_ty_2ad8d0_idx'),
        ),
    ]
